# Generated by Django 3.2.12 on 2023-01-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger_tools', '0015_metadata_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_video', models.FileField(null=True, upload_to='newVideo')),
            ],
        ),
    ]
